### PR TITLE
libpng.wrap: update to 1.6.37

### PR DESCRIPTION
**Pull request by alatiera**

### CODE REVIEW

**Comment by tp-m** [comment]
Did you test this?

I think the `fallback` in the `meson.build` also needs fixing for the dep variable renaming?

**Comment by alatiera** [comment]
I did and it seems to work, which is curious now that you mention the variable

```
alatiera@toolbox ~/P/c/freetype2 (alatiera/libpng-update)> 
rm -rf build && meson build -Dpng=enabled --wrap-mode=forcefallback
The Meson build system
Version: 0.56.0
Source dir: /home/alatiera/Projects/centricular/freetype2
Build dir: /home/alatiera/Projects/centricular/freetype2/build
Build type: native build
Project name: freetype2
Project version: 22.1.16
C compiler for the host machine: ccache cc (gcc 10.2.1 "cc (GCC) 10.2.1 20201016 (Red Hat 10.2.1-6)")
C linker for the host machine: cc ld.bfd 2.35-14
Host machine cpu family: x86_64
Host machine cpu: x86_64
Has header "unistd.h" : YES 
Has header "fcntl.h" : YES 
Has header "stdint.h" : YES 
Library bz2 found: YES
Header <bzlib.h> has symbol "BZ2_bzlibVersion" : YES 
Dependency harfbuzz skipped: feature harfbuzz disabled
Looking for a fallback subproject for the dependency zlib because:
Use of fallback dependencies is forced.

|Executing subproject zlib method meson 
|
|Project name: zlib
|Project version: 1.2.11
|C compiler for the host machine: ccache cc (gcc 10.2.1 "cc (GCC) 10.2.1 20201016 (Red Hat 10.2.1-6)")
|C linker for the host machine: cc ld.bfd 2.35-14
|Build targets in project: 1
|Subproject zlib finished.

Dependency zlib from subproject subprojects/zlib found: YES 1.2.11
Looking for a fallback subproject for the dependency libpng because:
Use of fallback dependencies is forced.

|Executing subproject libpng method meson 
|
|Project name: libpng
|Project version: 1.6.37
|C compiler for the host machine: ccache cc (gcc 10.2.1 "cc (GCC) 10.2.1 20201016 (Red Hat 10.2.1-6)")
|C linker for the host machine: cc ld.bfd 2.35-14
|Fetching value of define "__ANDROID__" :  
|Dependency zlib found: YES 1.2.11 (cached)
|Library m found: YES
|Fetching value of define "__ARM_NEON" :  
|Configuring libpng16.pc using configuration
|Configuring libpng.pc using configuration
|Build targets in project: 3
|Subproject libpng finished.

Dependency libpng from subproject subprojects/libpng-1.6.37 found: YES 1.6.37
Configuring ftconfig.h using configuration
Program include/configure-ftoption_h.py found: YES (/usr/bin/python3 /home/alatiera/Projects/centricular/freetype2/include/configure-ftoption_h.py)
Configuring ftoption.h.in with command
Configuring ftoption.h using configuration
subprojects/zlib/meson.build:33: DEPRECATION: Library z was passed to the "libraries" keyword argument of a previous call to generate() method instead of first positional argument. Adding zlib to "Requires" field, but this is a deprecated behaviour that will change in a future version of Meson. Please report the issue if this warning cannot be avoided in your case.
Build targets in project: 4

freetype2 22.1.16

  Subprojects
    libpng: YES
      zlib: YES

Found ninja-1.10.0.git.kitware.jobserver-1 at /usr/local/bin/ninja
Generating targets:   0%|                                                     |                                                                                 Writing build.ninja:   0%|                                                  | 0alatiera@toolbox ~/P/c/freetype2 (alatiera/libpng-update)> ninja -C build
ninja: Entering directory `build'
[9/77] Compiling C object subprojects/zlib/libz.so.1.2.11.p/gzlib.c.o
../subprojects/zlib/gzlib.c: In function ‘gz_open’:
../subprojects/zlib/gzlib.c:14:17: warning: implicit declaration of function ‘lseek’; did you mean ‘fseek’? [-Wimplicit-function-declaration]
   14 | #  define LSEEK lseek
      |                 ^~~~~
../subprojects/zlib/gzlib.c:252:9: note: in expansion of macro ‘LSEEK’
  252 |         LSEEK(state->fd, 0, SEEK_END);  /* so gzoffset() is correct */
      |         ^~~~~
[10/77] Compiling C object subprojects/zlib/libz.so.1.2.11.p/gzwrite.c.o
../subprojects/zlib/gzwrite.c: In function ‘gz_comp’:
../subprojects/zlib/gzwrite.c:89:20: warning: implicit declaration of function ‘write’; did you mean ‘fwrite’? [-Wimplicit-function-declaration]
   89 |             writ = write(state->fd, strm->next_in, put);
      |                    ^~~~~
      |                    fwrite
../subprojects/zlib/gzwrite.c: In function ‘gzclose_w’:
../subprojects/zlib/gzwrite.c:661:9: warning: implicit declaration of function ‘close’; did you mean ‘pclose’? [-Wimplicit-function-declaration]
  661 |     if (close(state->fd) == -1)
      |         ^~~~~
      |         pclose
[12/77] Compiling C object subprojects/zlib/libz.so.1.2.11.p/gzread.c.o
../subprojects/zlib/gzread.c: In function ‘gz_load’:
../subprojects/zlib/gzread.c:35:15: warning: implicit declaration of function ‘read’; did you mean ‘fread’? [-Wimplicit-function-declaration]
   35 |         ret = read(state->fd, buf + *have, get);
      |               ^~~~
      |               fread
../subprojects/zlib/gzread.c: In function ‘gzclose_r’:
../subprojects/zlib/gzread.c:651:11: warning: implicit declaration of function ‘close’; did you mean ‘pclose’? [-Wimplicit-function-declaration]
  651 |     ret = close(state->fd);
      |           ^~~~~
      |           pclose
[77/77] Linking target libfreetype.so.6.16.0
alatiera@toolbox ~/P/c/freetype2 (alatiera/libpng-update)> 
```

**Comment by tp-m** [comment]
Maybe that's because newer meson will use the var from the `provides` section, but older meson might not?

**Comment by alatiera** [comment]
No idea, tried 0.54.3 was still working. Ended up just renaming the variable.

**Pull request merged**
