### PR TITLE
meson: Disable freetype2 support when configuring harfbuzz subproject

### PR DESCRIPTION
**Pull request by xclaesse**

### CODE REVIEW

**Comment by xclaesse** [comment]
We have to disable fontconfig too because fontconfig unconditionally depends on freetype2.

I'm wondering if it makes sense for harfbuzz to lookup fontconfig when freetype2 is disabled?

**Comment by xclaesse** [comment]
See as well: https://github.com/harfbuzz/harfbuzz/pull/2498 and https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/37#note_472587

**Comment by nirbheek** [comment]
This makes sense to me.

**Comment by tp-m** [comment]
I guess it makes sense.

I wonder if in addition we should also default to `harfbuzz=disabled` in `meson_options.txt`.

The debian freetype packages are built without any harfbuzz/other-font deps, just libpng/libz.

**Comment by xclaesse** [comment]
> I wonder if in addition we should also default to `harfbuzz=disabled` in `meson_options.txt`.
> 
> The debian freetype packages are built without any harfbuzz/other-font deps, just libpng/libz.

I have no idea what enabling harfbuzz does in freetype2, maybe that can be discussed in a separate PR? I don't have write access to this repo to click the merge button.

**Pull request merged**
